version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run debug
    ports:
      - '9229:9229'
    tty: true
    volumes:
      - './src:/app/src'
      - './migrations:/app/migrations'
